# Generated by Django 6.0.1 on 2026-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightowlmainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('designer', 'Designer'), ('contractor', 'Contractor')], default='client', max_length=20),
        ),
    ]
