# Generated by Django 6.0 on 2026-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightowlmainapp', '0004_alter_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('designer', 'Designer'), ('contractor', 'Contractor')], default='client', max_length=20),
        ),
    ]
