# Generated by Django 6.0 on 2026-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightowlmainapp', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
