# Generated by Django 6.0 on 2026-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightowlmainapp', '0007_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
