# Generated by Django 6.0 on 2026-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_image_project_skills_alter_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
