# Generated by Django 6.0 on 2026-01-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_designerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
    ]
