# Generated by Django 6.0 on 2026-02-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_projectapplication_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio.project'),
        ),
    ]
